services:
  consumer:
    image: consumer
    
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5001
    networks:
      - postgres-network
    deploy:
      replicas: 3
    restart: always
    depends_on:
      - rabbitmq
      - pgbouncer
    
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    networks:
      - postgres-network
    depends_on:
      - pgbouncer
      - rabbitmq
    volumes:
      - ./API:/src/API
      - ./Models:/src/Models
      - ./Migrations:/src/Migrations
    restart: unless-stopped
      

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS=--auth=md5
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./initdb.d:/docker-entrypoint-initdb.d
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - postgres-network
    
  pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      
      - ADMIN_USERS=postgres,admin
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASSWORD=mypassword
      
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=10000
      - DEFAULT_POOL_SIZE=20
      - MIN_POOL_SIZE=5
      - RESERVE_POOL_SIZE=5
      - RESERVE_POOL_TIMEOUT=5
      - SERVER_LIFETIME=3600
      - SERVER_IDLE_TIMEOUT=600
      - SERVER_CONNECT_TIMEOUT=15
      - SERVER_LOGIN_RETRY=3
      - QUERY_WAIT_TIMEOUT=30
      - CLIENT_IDLE_TIMEOUT=600  # 10 минут
      - CLIENT_LOGIN_TIMEOUT=60
      - AUTODB_IDLE_TIMEOUT=3600
      - IGNORE_STARTUP_PARAMETERS=extra_float_digits
      - STATS_PERIOD=60
    ports:
      - "15432:5432"
    networks:
      - postgres-network
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres-network
    depends_on:
      - postgres
    
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - postgres-network

volumes:
  pgdata:
  pgadmin-data:
  rabbitmq_data:

networks:
  postgres-network:
    driver: bridge
  


